#config
Action = "status" # buy, sell, approve, allowance, addliquidity, removeliquidity, status, check, mine
Pair = "any/FSN" # any/fsn, usdt/fsn, eth/fsn, btc/fsn

[Mine]
TxMinAmount = 25.0 # 18 ANY
Reward = 17895
RewardToken = "ANY" # ANY
SellRewardToken = true
TxRate = 0.5
TxRewardPercent = 0.4
TxMinExpectPercent = 0.3 # 0.5 * (expect - volume)
Rebase = "false" # reward = 28800 * 5 * 0.2 * RabaseRate # CYC
StrategyReward = "liqudity" # percent/liquidity
StrategySycle = "blocknumber" # block/time
Blocks_mine = [50, 60, 70, 80, 95] # percent

[Exchange]
Amount_buy = 7045 # buy total per day with FSN
Amount_sell = 613 # 0: follow Amount_buy, almost all sold as mach as buying
Times_mine_sycle = 1 # 0: use Height, others: rand
Height = 87 # mine block number, int
Sycles = 1 # mine Sycles, int. 0 for ever

[Sync]
BlockStart = 3705000
BlockEnd = 3708342
ScanAllExchange = false

[Transfer]
To = [""]

[[Contracts]]
Pair     = "ANY/FSN"
Token    = "0x..." # mainnet FSN any
Exchange = "0x..." # mainnet FSN any

[Account]
Address = [
]

[Blockchain]
GatewayURL = "http://127.0.0.1:20812" # mainnet FSN
GasLimit   = 130000 # int
GasPrice   = 20000000000 # FSN: int, wei
DeadLine   = 1800 # second

[Blocktime]
Blocks_day = 86400 # 24h * 60 * 60
Blocks_sycle = 1800 # 30m * 60
Block_start = 1607594400 # 20201210 18:00:00
AverageBlockTime = 13

[Blocknumber]
Blocks_day = 6600
Blocks_sycle = 100 # rewards sycle
Block_start = 2552543
AverageBlockTime = 13

[Slipage]
Slipage = 0.05 #float

[Fee] # contract
Fee = 0.004 #float
